### ISSUE TITLE
Use of createScriptProcessor

### ISSUE THREAD

**Issue by Toad06** [ardean/jsGBC#1]
Hello,

I appreciate your emulator, he supports a lot of games and has great performances.

I think the only thing to reconsider would be the use of createScriptProcessor to generate audio because the spec says it will be removed in the future:
_There are also several features that have been deprecated from the Web Audio API but not yet removed, pending implementation experience of their replacements:
A ScriptProcessorNode interface, an AudioNode for generating or processing audio directly in JavaScript.
An AudioProcessingEvent interface, which is an event type used with ScriptProcessorNode objects._
https://webaudio.github.io/web-audio-api/#APIOverview

I'm not sure if there are currently any other solutions to get audio though.

Thanks.

**Comment by ardean** [comment]
Hi Toad06,

Nice to see you like jsGBC!
When I find some time I will consider your input.

Thank you for your suggestion.

**Comment by Toad06** [comment]
Thank you. 👍

**Comment by ardean** [comment]
This issue was moved to ardean/jsGBC-core#1
