### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Lorengamboa** [ardean/jsGBC#5]
Is it possible to load roam instanly without needing to loading it up from client?

Is there any guide to use this library?

**Comment by ardean** [comment]
Hi @Lorengamboa 

1. question:
You can open the .gbc / .gb files directly from your file explorer:
![image](https://cloud.githubusercontent.com/assets/17138728/23549173/2bbf8956-000b-11e7-8532-f908c81bfe69.png)

or using the menu item "Open ROM...":

![image](https://cloud.githubusercontent.com/assets/17138728/23549808/3b882ce6-000e-11e7-9d63-752740ba272c.png)


note that I'm currently working on the Windows and Linux build, so we have just a [MacOS Release](https://github.com/ardean/jsGBC/releases/tag/v0.4.1).

2. question:
There is currently no guide, but there will be one soon...

**Comment by Lorengamboa** [comment]
Lets say i want to save the game for the users so they can play anytime back when they return to the emulator.
Is there any way i can do that?

**Comment by ardean** [comment]
You can do this using **Save States**.
But they are currently broken, I will look at it this weekend.

A currently working solution could be the **Battery Data File**. This data is stored in the localstorage  when the game modifies the cartridge RAM, so you're savegame should be restored automatically like a real gameboy is doing.

**Comment by ardean** [comment]
@Lorengamboa if you need any features or help with you're project, don't hesitate to ask.

**Comment by Lorengamboa** [comment]
Thanks alot for answering!!!!

Well im planning to let users to choose games they desire to play so just
right after they choose a game it will either load the desired rom or a
saved game they have previously save.
Im planning to save the .save in the server.

What do you think?

Best regards!!

2017-03-03 17:47 GMT+01:00 ardean <notifications@github.com>:

**Comment by ardean** [comment]
You could use [jsGBC-core](https://github.com/ardean/jsGBC-core) in your project and load the game or savegame (from the server) into the gameboy.

Here is a basic [example](https://github.com/ardean/jsGBC-core/blob/master/index.js)-implementation and [this](https://ardean.github.io/jsGBC-core/) is the result.

**Comment by Lorengamboa** [comment]
Thanks for answering!
so i need to replace this part of the code with the path .save room?

const gameboy = new GameBoy($lcd.get(0));

2017-03-03 18:09 GMT+01:00 ardean <notifications@github.com>:

**Comment by ardean** [comment]
The constructor needs a [HTML canvas](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API) element as first argument.
once you've created your gameboy you can use the following api functions:

```javascript
const gameboy = new GameBoy(canvasElement);

gameboy.replaceCartridge(romFileContent); // insert / change rom file (.gbc, .gb)

gameboy.loadBatteryFileArrayBuffer(savFileContent); // load a battery file (.sav)
```

**UPDATE:**
note that the arguments are file contents ([Array Buffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer)). There are util functions you can use: 
```javascript
import { util } from "jsgbc-core";
util.uploadFile(["sav"]).then((savFileContent) => {
  // code from above
});
```

**Comment by Lorengamboa** [comment]
Appreciate your dedicattion!
I was wondering how can I compilate the project?

Greetings!

2017-03-05 21:51 GMT+01:00 ardean <notifications@github.com>:

**Comment by Lorengamboa** [comment]
I guess its a npm commant right?


2017-03-06 0:07 GMT+01:00 Lorenzo Gamboa <lorenzogamboagarcia@gmail.com>:

**Comment by Lorengamboa** [comment]
It seems like your are using typescript which im not familiar with.

Thanks alot for your help!

2017-03-06 0:08 GMT+01:00 Lorenzo Gamboa <lorenzogamboagarcia@gmail.com>:

**Comment by ardean** [comment]
I'm using JavaScript (ECMAScript 2016), so just the newest version of JavaScript. You can start the demo in jsGBC-core using:

```bash
npm start
```

but before you need to install the jspm_packages with:

```bash
jspm i
```

**Comment by Lorengamboa** [comment]
That is alot of help from you!

Tomorrow ill try it!

Thanks alot

2017-03-06 0:19 GMT+01:00 ardean <notifications@github.com>:

**Comment by Lorengamboa** [comment]
Ok one more question is it neccesary to inserta buffer into the api
methods? or is it possible to specify the path.

one more question is it neccesary to run the server to make it loadable?

Un saludo

2017-03-06 0:21 GMT+01:00 Lorenzo Gamboa <lorenzogamboagarcia@gmail.com>:

**Comment by ardean** [comment]
Yes, the only way to load ROMs or Battery Saves into the gameboy is using ArrayBuffers.

This is by design, because you have a lot of ways to load these data on your website.
(e.g. [fetch Api](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch), [xhr requests](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest), upload using [input type file](https://developer.mozilla.org/en-US/docs/Using_files_from_web_applications))

I could add a function to the util part of jsGBC-core:

```JavaScript
async function loadRomFromServerIntoGameboy(url) {
  const romFileContent = await util.fetchFileAsArrayBuffer(url);
  gameboy.replaceCartridge(romFileContent);
}
```

But until then you can use the following functions:

```JavaScript
async function loadRomFromServerIntoGameboy(url) {
  const romFileContent = await fetchFileAsArrayBuffer(url);
  gameboy.replaceCartridge(romFileContent);
}

async function fetchFileAsArrayBuffer(url) {
  const res = await fetch(url);
  return await res.arrayBuffer(); // Chrome, Opera, Firefox and Edge support only!
}
```

For question 2:

The only reasons you need a http server would be:
- loading HTML, CSS, JavaScript files and other assets for the website itself
- loading ROMs or Battery Saves from your server's database (using fetch api or other solutions)

jsGBC-core by itself does not require a http server, just a html canvas element to draw on.

If you do not want to use async / await, you can easily [replace](https://medium.com/@bluepnume/learn-about-promises-before-you-start-using-async-await-eb148164a9c8#.rwhc1ai14) them with Promises
